---

- name: Check for 'insights-client' RPM availability
  yum:
    list: insights-client
  register: yum_list_task

- name: Install 'insights-client' if it is available
  yum:
    name: insights-client
  when: yum_list_task.results|length > 0

- name: Set Insights Config to 'insights-client'
  set_fact:
    insights_name: 'insights-client'
  when: yum_list_task.results|length > 0

- name: Install 'redhat-access-insights' if 'insights-client' is not available
  yum:
    name: redhat-access-insights
  when: yum_list_task.results|length == 0

- name: Set Insights Config name to 'redhat-access-insights'
  set_fact:
    insights_name: 'redhat-access-insights'
  when: yum_list_task.results|length == 0

- name: Configure Red Hat Access Insights Client
  template: src=insights-client.conf.j2 dest=/etc/{{ insights_name }}/{{ insights_name }}.conf force=no

- name: Check status of Insights .unregister file
  stat: path=/etc/{{ insights_name }}/.unregistered
  register: unreg_file_task

- name: Check status of Insights .register file
  stat: path=/etc/{{ insights_name }}/.registered
  register: reg_file_task

- name: Unregister if we are setting the display_name, and we have already registered
  command: "{{ insights_name }} --unregister"
  when:
    - insights_display_name is defined
    - unreg_file_task.stat.exists == false
    - reg_file_task.stat.exists == true
  register: unreg_task

# Only register if this system hasn't been registered before
- name: Register to the Red Hat Access Insights Service
  command: "{{ insights_name }} --register {{ '--display-name='+insights_display_name if insights_display_name is defined else '' }} creates=/etc/{{ insights_name }}/.registered"
  when: unreg_file_task.stat.exists == false
  register: reg_task

